AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ECE30861 Team 18 Phase 2 - Serverless Application

Globals:
  Function:
    Runtime: python3.13
    Timeout: 10
    MemorySize: 512

Resources:

  # ExistingRestApi:
  #   Type: AWS::ApiGateway::RestApi
  #   Properties:
  #     Name: ExistingRestApiPlaceholder
  #   DeletionPolicy: Retain  # prevents deletion if stack deleted

  ece461Ph2Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Description: API Gateway for ECE461 phase 2 project
      Cors:
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  CreateArtifactLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: create_artifacts_lambda
      Handler: create_artifact_lambda.lambda_handler   # file.lambda_handler
      CodeUri: ./backend/app/handlers                  # directory with lambda_function.py
      Description: Lambda function to handle artifact creation requests.
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /artifact/{artifact_type}            # route on API Gateway
            Method: post                        # HTTP POST method
            RestApiId: !Ref ece461Ph2Api
      Environment:
        Variables:
          ENVIRONMENT: dev

  # CreateArtifactsLambda:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     FunctionName: create_artifacts_lambda
  #     Handler: create_artifacts_lambda.lambda_handler   # file.lambda_handler
  #     CodeUri: ./backend/app/handlers                  # directory with lambda_function.py
  #     Description: Lambda function to handle artifact creation requests.
  #     Events:
  #       ApiEvent:
  #         Type: Api
  #         Properties:
  #           Path: /artifact/{artifact_type}            # route on API Gateway
  #           Method: post                        # HTTP POST method
  #           RestApiId: !Ref ece461Ph2Api
  #     Environment:
  #       Variables:
  #         ENVIRONMENT: dev

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https:/${ece461Ph2Api}.execute-api.${AWS::Region}.amazonaws.com/dev/artifact"
