AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ECE30861 Team 18 Phase 2 - Serverless Application

Parameters:
  GITHUBTOKEN:
    Type: String
    NoEcho: true
    Description: GitHub token for metadata fetch
  HFTOKEN:
    Type: String
    NoEcho: true
    Description: Hugging Face token for model ingest

Globals:
  Function:
    Runtime: python3.11
    Timeout: 10
    MemorySize: 512
    Environment:
      Variables:
        S3_BUCKET: ece30861-team18-model-storage
        ENVIRONMENT: dev
        SECRET_NAME: DB_CREDS
        GITHUB_TOKEN: !Ref GITHUBTOKEN
        HF_TOKEN: !Ref HFTOKEN
    Layers:
      - arn:aws:lambda:us-east-1:422216016693:layer:psycopg2-py313-layer-new2:1

Resources:

  #########################################################
  # API Gateway
  #########################################################
  ece461Ph2Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Description: ECE461 Phase 2 API Gateway (OpenAPI Spec)

  #########################################################
  # LAMBDA FUNCTIONS
  #########################################################

  HealthLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: health_lambda
      Handler: handlers/health_lambda.lambda_handler
      CodeUri: ./backend/app
      Runtime: python3.11
      Description: Health check endpoint
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /health
            Method: get
            RestApiId: !Ref ece461Ph2Api
    Policies:
      - AWSLambdaBasicExecutionRole

  HealthComponentLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: health_components_lambda
      Handler: handlers/health_components_lambda.lambda_handler
      CodeUri: ./backend/app
      Runtime: python3.11
      Description: Return per-component health diagnostics
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /health/components
            Method: get
            RestApiId: !Ref ece461Ph2Api
    Policies:
      - AWSLambdaBasicExecutionRole

  CreateArtifactLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: create_artifact_lambda
      Handler: handlers/create_artifact_lambda.lambda_handler
      CodeUri: ./backend/app
      Description: Lambda for creating artifacts
      Environment:
        Variables:
          INGEST_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/422216016693/model-ingestion-queue
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /artifact/{artifact_type}
            Method: post
            RestApiId: !Ref ece461Ph2Api
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:DB_CREDS-*
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: arn:aws:sqs:us-east-1:422216016693:model-ingestion-queue
  ListArtifactsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: list_artifacts_lambda
      Handler: handlers/list_artifacts_lambda.lambda_handler
      CodeUri: ./backend/app
      Description: Lambda for listing artifacts
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /artifacts
            Method: post
            RestApiId: !Ref ece461Ph2Api
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:DB_CREDS-*

  GetArtifactLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get_artifact_lambda
      Handler: handlers/get_artifact_lambda.lambda_handler
      CodeUri: ./backend/app
      Description: Lambda for getting an artifact
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /artifacts/{artifact_type}/{id}
            Method: get
            RestApiId: !Ref ece461Ph2Api
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:DB_CREDS-*

  UpdateArtifactLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: update_artifact_lambda
      Handler: handlers/update_artifact_lambda.lambda_handler
      CodeUri: ./backend/app
      Description: Lambda for updating artifact
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /artifacts/{artifact_type}/{id}
            Method: put
            RestApiId: !Ref ece461Ph2Api
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:DB_CREDS-*

  DeleteArtifactLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: delete_artifact_lambda
      Handler: handlers/delete_artifact_lambda.lambda_handler
      CodeUri: ./backend/app
      Description: Lambda for deleting artifact
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /artifacts/{artifact_type}/{id}
            Method: delete
            RestApiId: !Ref ece461Ph2Api
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:DB_CREDS-*

  ResetRegistryLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: reset_registry_lambda
      Handler: handlers/reset_registry_lambda.lambda_handler
      CodeUri: ./backend/app
      Description: Lambda for resetting registry
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /reset
            Method: delete
            RestApiId: !Ref ece461Ph2Api
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:DB_CREDS-*
Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ece461Ph2Api}.execute-api.${AWS::Region}.amazonaws.com/dev"
