AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ECE30861 Team 18 Phase 2 - Serverless Application

Globals:
  Function:
    Runtime: python3.13
    Timeout: 10
    MemorySize: 512
    Environment:
      Variables:
        S3_BUCKET: ece30861-team18-model-storage
        ENVIRONMENT: dev
        SECRET_NAME: DB_CREDS
    Layers:
      - arn:aws:lambda:us-east-1:422216016693:layer:psycopg2-py313-layer-new2:1

Resources:

  #########################################################
  # API Gateway
  #########################################################
  ece461Ph2Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Description: ECE461 Phase 2 API Gateway (OpenAPI Spec)
      DefinitionBody:
        openapi: 3.0.2
        info:
          title: ECE461 Phase 2 API
          version: 3.3.1

        components:
          schemas:
            ArtifactType:
              type: string
              enum: [model, dataset, code]

            AuthenticationToken:
              type: string
              description: Authorization token passed via X-Authorization header.

            ArtifactData:
              type: object
              required: [url]
              properties:
                url:
                  type: string
                  format: uri

            Artifact:
              type: object
              required: [metadata, data]
              properties:
                metadata:
                  type: object
                  properties:
                    name:
                      type: string
                    id:
                      type: integer
                    type:
                      $ref: "#/components/schemas/ArtifactType"
                data:
                  type: object
                  properties:
                    url:
                      type: string
                      format: uri

        paths:
          /artifacts:
            post:
              operationId: ArtifactsList
              summary: Get artifacts
              description: Get artifacts matching the query.
              parameters:
                - name: X-Authorization
                  in: header
                  required: true
                  schema:
                    $ref: "#/components/schemas/AuthenticationToken"
              responses:
                "200":
                  description: List of artifacts
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ListArtifactsLambda.Arn}/invocations
                httpMethod: POST
                type: aws_proxy

          /reset:
            delete:
              operationId: RegistryReset
              summary: Reset the registry
              description: Reset registry to default state.
              parameters:
                - name: X-Authorization
                  in: header
                  required: true
                  schema:
                    $ref: "#/components/schemas/AuthenticationToken"
              responses:
                "200":
                  description: Registry is reset
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ResetRegistryLambda.Arn}/invocations
                httpMethod: POST
                type: aws_proxy

          /artifacts/{artifact_type}/{id}:
            get:
              operationId: ArtifactRetrieve
              summary: Retrieve artifact
              description: Get artifact by ID.
              parameters:
                - name: artifact_type
                  in: path
                  required: true
                - name: id
                  in: path
                  required: true
              responses:
                "200":
                  description: Artifact found
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetArtifactLambda.Arn}/invocations
                httpMethod: POST
                type: aws_proxy

            put:
              operationId: ArtifactUpdate
              summary: Update artifact
              description: Update artifact contents.
              parameters:
                - name: artifact_type
                  in: path
                  required: true
                - name: id
                  in: path
                  required: true
              responses:
                "200":
                  description: Artifact updated
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateArtifactLambda.Arn}/invocations
                httpMethod: POST
                type: aws_proxy

            delete:
              operationId: ArtifactDelete
              summary: Delete artifact
              description: Delete artifact by ID.
              parameters:
                - name: artifact_type
                  in: path
                  required: true
                - name: id
                  in: path
                  required: true
              responses:
                "200":
                  description: Artifact deleted
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeleteArtifactLambda.Arn}/invocations
                httpMethod: POST
                type: aws_proxy

          /artifact/{artifact_type}:
            post:
              operationId: ArtifactCreate
              summary: Register new artifact
              description: Register new artifact by providing a URL.
              parameters:
                - name: artifact_type
                  in: path
                  required: true
                - name: X-Authorization
                  in: header
                  required: true
              responses:
                "201":
                  description: Artifact created
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateArtifactLambda.Arn}/invocations
                httpMethod: POST
                type: aws_proxy

      Cors:
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  #########################################################
  # LAMBDA FUNCTIONS
  #########################################################

  CreateArtifactLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: create_artifact_lambda
      Handler: create_artifact_lambda.lambda_handler
      CodeUri: ./backend/app/handlers
      Description: Lambda for creating artifacts
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /artifact/{artifact_type}
            Method: post
            RestApiId: !Ref ece461Ph2Api
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:DB_CREDS-*

  ListArtifactsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: list_artifacts_lambda
      Handler: list_artifacts_lambda.lambda_handler
      CodeUri: ./backend/app/handlers
      Description: Lambda for listing artifacts
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /artifacts
            Method: post
            RestApiId: !Ref ece461Ph2Api
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:DB_CREDS-*

  GetArtifactLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get_artifact_lambda
      Handler: get_artifact_lambda.lambda_handler
      CodeUri: ./backend/app/handlers
      Description: Lambda for getting an artifact
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /artifacts/{artifact_type}/{id}
            Method: get
            RestApiId: !Ref ece461Ph2Api
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:DB_CREDS-*

  UpdateArtifactLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: update_artifact_lambda
      Handler: update_artifact_lambda.lambda_handler
      CodeUri: ./backend/app/handlers
      Description: Lambda for updating artifact
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /artifacts/{artifact_type}/{id}
            Method: put
            RestApiId: !Ref ece461Ph2Api
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:DB_CREDS-*

  DeleteArtifactLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: delete_artifact_lambda
      Handler: delete_artifact_lambda.lambda_handler
      CodeUri: ./backend/app/handlers
      Description: Lambda for deleting artifact
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /artifacts/{artifact_type}/{id}
            Method: delete
            RestApiId: !Ref ece461Ph2Api
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:DB_CREDS-*

  ResetRegistryLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: reset_registry_lambda
      Handler: reset_registry_lambda.lambda_handler
      CodeUri: ./backend/app/handlers
      Description: Lambda for resetting registry
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /reset
            Method: delete
            RestApiId: !Ref ece461Ph2Api
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:DB_CREDS-*
  
  
  #########################################################
  # LAMBDA INVOKE PERMISSIONS (for API Gateway)
  #########################################################

  CreateArtifactPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt CreateArtifactLambda.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ece461Ph2Api}/*/*/*

  ListArtifactsPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt ListArtifactsLambda.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ece461Ph2Api}/*/*/*

  GetArtifactPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt GetArtifactLambda.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ece461Ph2Api}/*/*/*

  UpdateArtifactPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt UpdateArtifactLambda.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ece461Ph2Api}/*/*/*

  DeleteArtifactPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt DeleteArtifactLambda.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ece461Ph2Api}/*/*/*

  ResetRegistryPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt ResetRegistryLambda.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ece461Ph2Api}/*/*/*


Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ece461Ph2Api}.execute-api.${AWS::Region}.amazonaws.com/dev"
