AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ECE30861 Team 18 Phase 2 - Serverless Application

Globals:
  Function:
    Runtime: python3.13
    Timeout: 10
    MemorySize: 512

Resources:

  ExistingRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: ExistingRestApiPlaceholder
    DeletionPolicy: Retain     # prevents deletion if stack deleted

  CreateArtifactFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: create_artifact_lambda
      Handler: create_artifact_lambda.lambda_handler   # file.lambda_handler
      CodeUri: ./backend/app/handlers                  # directory with lambda_function.py
      Description: Lambda function to handle artifact creation requests.
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /artifact/{artifact_type}            # route on API Gateway
            Method: post                        # HTTP POST method
            RestApiId: !Ref ExistingRestApi
      Environment:
        Variables:
          ENVIRONMENT: dev

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https:/cfehic5hh2.execute-api.${AWS::Region}.amazonaws.com/dev/artifact"
