# We'll use this file for the CI/CD pipeline in milestone 2
name: main pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GEN_AI_STUDIO_API_KEY: ${{ secrets.GEN_AI_STUDIO_API_KEY }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run MyPy
      run: mypy app/
    - name: Run tests
      run: |
        python -m pytest --cov=app --cov-report=term-missing tests/